version: "3.9"
services:
  ssdq_postgres:
    container_name: ssdq_postgres_container
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: "ssdq"
      POSTGRES_USER: "ssdq_admin"
      POSTGRES_PASSWORD: "admin_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_scripts/:/docker-entrypoint-initdb.d/
      - ssdqdb-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssdq_admin -d ssdq"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.16.1.4
      
  ssdq_server:
    container_name: ssdq_server_container
    image: ssdq_server
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/dqflask/config
      # - ./cert:/app/dqflask/cert
    depends_on:
      ssdq_postgres:
        condition: service_healthy
      
volumes:
  ssdqdb-data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
      